[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.11"
enum_variant_name = { git = "https://github.com/bowarc/crates", package = "enum_variant_name" }

[dev-dependencies]
insta = "1.42.1"
